verion: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    working_dirctory: ~/projects/rails-practice1/src
    steps:
      - checkout:
        path: ~/projects/rails-practice1
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7
      - image: circleci/mysql:5.5
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATA_BASE_HOST: "127.0.0.1" 
      RAILS_ENV: test
    working_directory: ~/projects/rails-practice1/src
    steps:
      - checkout:
        path: ~/projects/rails-practice1
      - ruby/install-deps  
      - run:
          name: Database set up
          command: bundle exec rails db:mitrate
      - run:
          name: test
          command: bundle exec rake test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
      - test:
          reqires:
            - build
